[build]
  command = "NEXT_PUBLIC_GEMINI_API_KEY=$GEMINI_API_KEY npm run build"
  publish = ".next"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[plugins]]
  package = "@netlify/plugin-nextjs"